version: "3.8"
services:
  app:
    build: .
    container_name: launchscore-backend
    restart: unless-stopped
    env_file: .env
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: launchscore-nginx
    restart: unless-stopped
    ports:
      - "5000:80" # Expose backend API on port 5000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
